ujrateszt

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -8,6 +8,17 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Test secrets and creat .env
+      run: |
+        secrets=("SECRET_1" "SECRET_2" "SECRET_3")
+        for secret in "${secrets[@]}"; do
+          if [[ -z "${!secret}" ]]; then
+            echo "ERROR: $secret not set"
+            exit 1
+          fi
+          echo "${secret}=${{ secrets.${secret} }}" >> .env
+        done
+
     - name: Checkout code
       uses: actions/checkout@v2
 
@@ -16,16 +27,6 @@ jobs:
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
-
-    - name: Create env
-      run: |
-        secrets=("SECRET_1" "SECRET_2" "SECRET_3")
-        for secret in "${secrets[@]}"; do
-          if [[ -z "${!secret}" ]]; then
-            echo "ERROR: $secret not set"
-            exit 1
-          fi
-        done
 
     - name: Build and push Docker image
       uses: docker/build-push-action@v2
